DROP SCHEMA IF EXISTS IMOCK;

CREATE SCHEMA IMOCK;
CREATE TABLE IMOCK.ACCOUNTS(
    EMAIL VARCHAR(30),
    DOCUMENTS INT,
    INTERVIEWS INT,
    RESUME TEXT,
    JOBPOST TEXT,
    PRIMARY KEY(EMAIL)
);
CREATE TABLE IMOCK.USER_QUESTIONS(
    EMAIL VARCHAR(30),
    QUESTION TEXT,
    QUESTION_TYPE INT,
    FOREIGN KEY (EMAIL) REFERENCES IMOCK.ACCOUNTS (EMAIL) ON DELETE CASCADE
);
CREATE TABLE IMOCK.RECORDS(
    EMAIL VARCHAR(30),
    RECORDED_TIME DATETIME,
    EXPIRE INT,
    JOB TEXT,
    RESUME TEXT,
    JOBPOST TEXT,
    PRIMARY KEY(EMAIL,RECORDED_TIME),
    FOREIGN KEY (EMAIL) REFERENCES IMOCK.ACCOUNTS (EMAIL) ON DELETE CASCADE
);
CREATE TABLE IMOCK.ANSWERED_QUESTIONS(
    EMAIL VARCHAR(30),
    RECORDED_TIME DATETIME,
    QUESTION TEXT,
    ANSWER TEXT,
    REVIEW TEXT,
    EXAMPLE TEXT,
    FOREIGN KEY (EMAIL,RECORDED_TIME) REFERENCES IMOCK.RECORDS (EMAIL,RECORDED_TIME) ON DELETE CASCADE
);